project:
  type: website
  output-dir: docs


website:
  title: "stunning-octo-adventure"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - python.qmd
      - r.qmd
      - javascript.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



